name: Publish Image to GitHub Packages

on:
  push:
    branches: 
      - main
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SvelteKit Build
        run: npm i && npm run build
        env:
          SVELTEKIT_BUILD_TYPE: static

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/svelte-ui-template:latest
